site_name: TeachMe.Codes


theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni


nav:
- Home: index.md
- Why  Linux?: WhyLinux.md


- Getting started:
  - Guide to starting Linux: GettingStarted/Linux.md
  - Guide to Shell Scripts: GettingStarted/Shell.md
  - Installing Linux : GettingStarted/Install.md
  - Lunching an EC2 (Linux) instance in AWS Cloud: GettingStarted/cloud.md
  - How to Git: GettingStarted/git.md

  
- File and Permission:
  - How to Create and Edit Text Files: 1-create-edit-textFiles.md
  - How to Search Files: 2-search-files.md
  - Redirection, Compare Text and Binary File: 3-redirection.md
  - Archive, Compress, Unpack and Decompress Files: 4-archive-compress.md
  - List, Set and Change Standard File Permissions : 5-file-permissions.md
  - Transfer Files Securely via SFTP/SCP: 6-transfer-files.md


Process:
  - Change the Priority of a Process: 7-priority-process.md
  - Manage the Startup Processes and Services: 8-start-processes-services.md
  - Managing User Processes: 9-user-processes.md


Installing Software:
  - Installing Software Packages: B-installing-software.md
  - Stting Standard File Permissions : A-file-permissions-ownership.md
  - Shell commands notation: C-shell.md


User Accounts:
  - Create, Delete and Modify Local User Accounts: D-user-accounts.md
  - Create, Delete and Modify Local Groups : D-user-accounts.md


Network:
  - Configure Network Services : E-1-Network-start.md
  - Network Packet Filtering: E-2-Network-Packet-Filtering.md
  - Network Performance : E-3-Network-Performance.md
  - Network Firewall : E-4-Network-Firewall.md
  - Network Sharing : E-5-Network-Sharing.md
  - Network SMTP: E-6-Network-SMTP.md
  - Network SSH: E-7-Network-SSH.md
  - Network HTTP : E-8-Network-HTTP-Server.md
  - Network SSL : E-9-Network-SSL-Apache.md
  - Network Virtual Web Hosting: E-10-Network-Virtual-Web-Host.md



